const LinkedList = require('./linkedList.js');
const list = new LinkedList();
console.log(list.isEmpty());
list.add(10);
list.printList();
console.log(list.listSize());
list.add(20);
list.add(30);
list.add(40);
list.add(50);
list.printList();
console.log("is element removed ? " + list.removeData(50));
list.printList();
console.log("Index of 40 " + list.indexOf(40));
list.insertAt(60, 2);
list.printList();
console.log("is List Empty ? " + list.isEmpty());
console.log(list.removeFrom(3));
list.printList();
